version: "3"
services:
  gin:
    build:
      context: .
      dockerfile: images/gin/Dockerfile
    volumes:
      - ./server:/server
    depends_on:
      - mysql
      - redis
    environment:
      GO111MODULE: "on"
  cms:
    build:
      context: .
      dockerfile: images/cms/Dockerfile
    volumes:
      - ./cms:/app
    depends_on:
      - gin
  web:
    build:
      context: .
      dockerfile: images/web/Dockerfile
    volumes:
      - ./web:/app
    depends_on:
      - gin
  nginx:
    build:
      context: .
      dockerfile: images/nginx/Dockerfile
    volumes: 
      - ./images/nginx/conf/:/etc/nginx/conf.d/
    depends_on:
      - gin
      - web
      - cms
    ports:
      - 80:80
    environment:
      TZ: "Asia/Tokyo"
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_USER: tester
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql:rw
      - ./images/mysql/default_my.cnf:/etc/mysql/conf.d/default_my.cnf
      - ./images/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:alpine
    volumes:
      - ./images/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
volumes:
   db:

